spring.application.name=StudentManagement2026ver
spring.profiles.active=local
# dummy
spring.datasource.url=jdbc:mysql://localhost:3306/xxx
spring.datasource.username=xxx
spring.datasource.password=xxx
# MyBatis
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=raisetech.StudentManagement2026ver.data
# 404 Not Found
spring.mvc.throw-exception-if-no-handler-found=true
# disable static resources
spring.web.resources.add-mappings=false